### ISSUE TITLE
2.0.2 SNAPSHOT r5c38483 possibly reports incorrect file and directory scan count

### ISSUE THREAD

**Issue by bkcsfi** [pmonks/alfresco-bulk-import#57]
using this version to import  a total of 195614 folders, 565921 pdf files and 772691 properties.xml files

The statistics reported on the job status screen appears to over-state the number of files and directories scanned. 

```
Status:     Succeeded
Initiating User:    admin
Source Name:    Default
Source directory    /import/Company Home/User Homes
Target Space:   /Company Home/User Homes
Import Type:    Streaming
Dry run:    No
Batch Weight:   100
Threads:    0 active of 0 total
Start Date:     2016-07-12T12:25:51Z
Scan End Date:  2016-07-12T15:14:21Z
End Date:   2016-07-12T16:47:39Z
Scan Duration:  02h 48m 29s 530.760ms
Duration:   04h 21m 47s 459.256ms
Currently Importing:    

Source (read) Statistics
Directories scanned:    391220  38.698 / sec
Files scanned:  2699544 267.03 / sec

Target (write) Statistics
Aspects associated: 6778444 431.543 / sec
Batches completed:  7728    0.492 / sec
Batches submitted:  7728    0.492 / sec
Bytes imported: 36268718407 2309012.5 / sec
Content streamed:   577081  36.739 / sec
In place content linked:    0   0 / sec
Metadata properties imported:   14374735    915.153 / sec
Nodes imported: 772691  49.193 / sec
Nodes skipped:  0   0 / sec
Out-of-order retries:   0   0 / sec
Versions imported:  0   0 / sec
```

the final node  count reported (772691) is correct

```
2016-07-12 12:47:39,350  INFO  [bulkimport.impl.LoggingBulkImportCompletionHandler] [BulkImport-Scanner] BULKIMPORT: Streaming bulk import completed (Succeeded) in 04h 21m 47s 459.256ms.
Batches:                7728 imported of 7728 submitted (0.492 / sec)
Nodes:                  772691 (49.193 / sec)
Bytes:                  36268718407 (2309012.500 / sec)
Versions:               0
Metadata properties:    14374735
Files:                  0 in-place, 577081 streamed, 0 skipped
Out-of-order batches:   0
```

(previously reported in #55)

**Comment by pmonks** [comment]
The source content set is scanned twice - once for folders and once for files, which explains most of what you're seeing (`195614 X 2 = 391228`, which is close to 391220).  The delta of 4 (`8 ÷ 2`) may be due to permissions (files & folders the tool doesn't have permission to read are skipped, with a warning in the log, although that may not be showing up given the odd logging behaviour we saw in issue #55), or may be due to the way you're counting the folders on-disk (the root folder that you specify in the UI, for example, is not counted by the tool).

I'll add this as an item to the [FAQ.](https://github.com/pmonks/alfresco-bulk-import/wiki/FAQ).

**Comment by pmonks** [comment]
Addressed in [this FAQ item](https://github.com/pmonks/alfresco-bulk-import/wiki/FAQ#q-why-is-the-count-of-folders-scanned-so-much-higher-than-the-actual-number-of-folders-on-disk-in-the-source-content-set).
